### ISSUE TITLE
retrain jsbd, jtbd & jpos models

### ISSUE THREAD

**Issue by fmatthies** [JULIELab/jcore-base#48]
due to changes in the names for some packages, we need to retrain the models (biomed & medical) and deploy them with new projects for 2.3.0

**Comment by egrygorova** [comment]
Results of 90-10 for JTBD:

* ------------------------------------
* critical decisions: 22790
* correct decisions: 21955
* fp: 400
* fn: 435
* R: 0.9805716837874051
* P: 0.9821069112055468
* F: 0.9813386970611242
* ACC = 0.9633611232996928
* ------------------------------------

Results of 90-10 for JSBD:

performing evaluation on 90/10 split
Error: no test files for this split. Number of files in directory might be too small.

**Comment by egrygorova** [comment]
Results of 90-10 for JTBD FRAMED:

* ------------------------------------
* critical decisions: 1667
* correct decisions: 1667
* fp: 0
* fn: 0
* R: 1.0
* P: 1.0
* F: 1.0
* ACC = 1.0
* ------------------------------------

**Comment by fmatthies** [comment]
Hmm, the results for FRAMED look too good to be true.
Did you do a 10-fold cross validation (same for the biomed corpus) or just a random 90-10 split test?

**Comment by egrygorova** [comment]
it was for a random 90-10 test
the 10-fold cross validation for JTBD Framed resulted in this..

* ------------------------------------
* critical decisions: 1667
* correct decisions: 1667
* fp: 0
* fn: 0
* R: 1.0
* P: 1.0
* F: 1.0
* ACC = 1.0
* ------------------------------------

ACC in round 0: 1,000
ACC in round 1: 0,999
ACC in round 2: 1,000
ACC in round 3: 1,000
ACC in round 4: 1,000
ACC in round 5: 1,000
ACC in round 6: 1,000
ACC in round 7: 1,000
ACC in round 8: 1,000
ACC in round 9: 1,000


------------------------------------
avg accuracy: 1,000
avg F-score: 1,000

the result for evaluation on the previous trained model was this:

* ------------------------------------
* critical decisions: 16444
* correct decisions: 16442
* fp: 2
* fn: 0
* R: 1.0
* P: 0.9998783750912187
* F: 0.9999391838472298
* ACC = 0.9998783750912187
* ------------------------------------

**Comment by egrygorova** [comment]
Results of Evaluation on a pretrained model for JSBD FRAMED:

all : 6282
corr: 6088
fp :152
fn :42
R :0.9931484502446982
P :0.9756410256410256
F :0.9843168957154406
ACC : 0.9691181152499204


Accuracy on pretrained model: 0.9691181152499204

**Comment by egrygorova** [comment]
Results of Evaluation on a pretrained model for JSBD (biomedical):

all : 6282
corr: 5846
fp :106
fn :330
R :0.9465673575129534
P :0.9821908602150538
F :0.9640501319261214
ACC : 0.9305953517987902


Accuracy on pretrained model: 0.9305953517987902

**Comment by egrygorova** [comment]
Results of Evaluation on a pretrained model for JTBD (biomedical):

* ------------------------------------
* critical decisions: 228759
* correct decisions: 225223
* fp: 2040
* fn: 1496
* R: 0.9934015234717867
* P: 0.9910236158107567
* F: 0.9922111449352617
* ACC = 0.9845426846594014
* ------------------------------------

**Comment by egrygorova** [comment]
a config file for jpos is still missing

**Comment by egrygorova** [comment]
The following Error occurs, when I'm trying to train the model for jpos:

java -jar jars/jpos-2.3.0-SNAPSHOT-jar-with-dependencies.jar t corpora/framedposcorpus/pos.train jpos-framed framed.conf 


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
   * training model... on 7560 sentences
Exception in thread "main" java.lang.NegativeArraySizeException
	at cc.mallet.classify.MaxEntOptimizableByLabelLikelihood.<init>(MaxEntOptimizableByLabelLikelihood.java:70)
	at cc.mallet.classify.MaxEntTrainer.getOptimizable(MaxEntTrainer.java:121)
	at cc.mallet.classify.MaxEntTrainer.getOptimizable(MaxEntTrainer.java:110)
	at cc.mallet.classify.MaxEntTrainer.getOptimizer(MaxEntTrainer.java:164)
	at cc.mallet.classify.MaxEntTrainer.train(MaxEntTrainer.java:227)
	at cc.mallet.classify.MaxEntTrainer.train(MaxEntTrainer.java:221)
	at de.julielab.jcore.ae.jpos.tagger.POSTagger.train(POSTagger.java:162)
	at de.julielab.jcore.ae.jpos.main.JPOSApplication.train(JPOSApplication.java:197)
	at de.julielab.jcore.ae.jpos.main.JPOSApplication.main(JPOSApplication.java:104)

**Comment by egrygorova** [comment]
Results of Evaluation on a pretrained model for JTBD FRAMED:

* ------------------------------------
* critical decisions: 16444
* correct decisions: 16442
* fp: 2
* fn: 0
* R: 1.0
* P: 0.9998783750912187
* F: 0.9999391838472298
* ACC = 0.9998783750912187
* ------------------------------------

**Comment by fmatthies** [comment]
jsbd & jtbd models are uploaded. The FRAMED `train.tok` is not tokenized (as stated in the README); that's why the results looked too good to be true.

**Comment by egrygorova** [comment]
I thought that there isn't any pos corpus for biomedical english? only a FRAMED

**Comment by egrygorova** [comment]
I made a pull request for JSBD & JTBD Biomed in jcore-projects
There is still an error with JPOS...

**Comment by fmatthies** [comment]
Can you look at the error yourself? Has your training corpus the right format?

**Comment by fmatthies** [comment]
added newly trained jpos framed model to branch "retrainModels_issue48". Accuracy is the same as reported in the project readme.

**Comment by fmatthies** [comment]
Please retrain the test models for jsbd and jtbd as well.
Data is under `src/main/resources` (jcore-base).

**Comment by fmatthies** [comment]
could you also report the final figures for `jsbd` & `jtbd` x-fold-crossvalidation on the biomed corpus?
I'm not quite sure where and what they are.

**Comment by egrygorova** [comment]
you mean the test data is under `src/test/resources/testdata/train`?

**Comment by egrygorova** [comment]
Results for 10-folds-crossvalidation for JTBD:

* ------------------------------------
* critical decisions: 22805
* correct decisions: 21979
* fp: 417
* fn: 409
* R: 0.981731284616759
* P: 0.9813806036792284
* F: 0.9815559128260092
* ACC = 0.9637798728349046
* ------------------------------------

ACC in round 0: 0,952
ACC in round 1: 0,815
ACC in round 2: 0,960
ACC in round 3: 0,964
ACC in round 4: 0,957
ACC in round 5: 0,957
ACC in round 6: 0,960
ACC in round 7: 0,965
ACC in round 8: 0,948
ACC in round 9: 0,964


------------------------------------
avg accuracy: 0,944
avg F-score: 0,971
------------------------------------

**Comment by egrygorova** [comment]
Results for evaluation on a pretrained model for JSBD Biomed (X-Folds was not possible again...):

all : 79694
corr: 73457
fp :1273
fn :4964
R :0.9367006286581401
P :0.9829653418974976
F :0.9592754862847777
ACC : 0.9217381484176977


Accuracy on pretrained model: 0.9217381484176977

**Comment by fmatthies** [comment]
> In SentenceSplitterApplication steht:
> private final static String doPostprocessing =
> "de.julielab.jcore.ae.jsbd.PostprocessingFilters.BiomedPostprocessingFilter";
> 
> Geprüft wird in SentenceSplitter auf (mit doPostprocessing als filterName):
> (filterName.toLowerCase()).equals("biomed")
> 
> Das führt dazu, dass ohne Änderungen keines der
> Post-processing-Verfahren aktiv wird. Interessanterweise verbessert dies
> die Ergebnisse auf FRAMED:
> 
> Alte Ergebnisse aus der jcore-projects Seite:
> Accuracy: 0.985 F-Measure: 0.993
> 
> Medical-Abkürzungen, Post-processing:
> avg accuracy: 0,986
> avg f-score: 0,993
> 
> Medical-Abkürzungen, kein Post-processing
> avg accuracy: 0,991
> avg f-score: 0,995
> 
> Medical-Abkürzungen, kein Post-processing, Unicode-Änderungen
> avg accuracy: 0,991
> avg f-score: 0,995

**Comment by fmatthies** [comment]
@egrygorova maybe you code look into the code and figure out, why it's npt working? It's probably to do with the corpus? You'll likely need to split it.

**Comment by egrygorova** [comment]
ok, I looked at it and I think it cannot perform the cross validation because of that condition:

if (n > (abstractArray.length / 2) || n > 10 || n < 2) {
			System.err.println("Error: cannot perform " + n + " cross-validation rounds. Choose n in [2:10].");
			System.exit(-1);
		}

I only have one File `biotoken.sent` in the abstract Array (it contains the files of my directory, where I have the corpus) and (abstractArray.length / 2) evaluates to 0 because 1/2 = 0 (integer division). so the 
condition always evaluates to false, because I can choose n in [2;10] and it is always bigger than 0.

so I changed the condition in 
if (n < (abstractArray.length / 2) || n > 10 || n < 2)
not sure, if it's right, the first part of the condition makes no sense to me anyway, but the evaluation seems to work now

**Comment by egrygorova** [comment]
oh okay, you're right, the files aren't splitted,
when I remove the first part of the condition
		if (`n < (abstractArray.length / 2)` || n > 10 || n < 2) {
			System.err.println("Error: cannot perform " + n + " cross-validation rounds. Choose n in [2:10].");
			System.exit(-1);
		}

the evaluation is running now, but it doesn't evaluate properly

for example, with n = 2:
performing cross-validation
number of files in directory: 2
size of each/last round: 1/1

training size: 1
prediction size: 1

the training size and the prediction size are totally wrong, there are just the number of the files (corpus), not the sentences

**Comment by egrygorova** [comment]
it's strange, because both files are splitted by sentences

**Comment by fmatthies** [comment]
I don't know where my comment went... here it is either way (again?):
> Well, good catch. But please revert your changes to the code! :)
It's better (and where I wanted to lead you - as mentioned in a previous comment) that you split up the "biotoken.sent" file in mutliple files! (This is doable from the command line: have a look at "split", e.g. https://wiki.ubuntuusers.de/split/).

**Comment by egrygorova** [comment]
oh ok, I wanna try it

**Comment by egrygorova** [comment]
Results for 2-folds cross validation for JSBD BioMed, 10-folds will come soon:

all : 69589
corr: 69308
fp :180
fn :101
R :0.9985448572951634
P :0.9974096246833986
F :0.9979769181479802
ACC : 0.9959620054893733
0: 0,997
1: 0,996
avg accuracy: 0,997
avg f-score: 0,998


Accuracy on cross validation: 0.996668500098512

**Comment by egrygorova** [comment]
Results for 10-folds cross validation for JSBD BioMed:

all : 12446
corr: 12427
fp :17
fn :2
R :0.9998390860085284
P :0.9986338797814208
F :0.999236119486994
ACC : 0.9984734051100755
0: 0,999
1: 0,996
2: 0,997
3: 0,997
4: 0,997
5: 0,996
6: 0,999
7: 0,998
8: 1,000
9: 0,998
avg accuracy: 0,998
avg f-score: 0,999


Accuracy on cross validation: 0.9978995138885253

**Comment by fmatthies** [comment]
> all : 69589
corr: 69308

> all : 12446
corr: 12427

why do these differ? There should be an equal amount of sentences... How did you split?

**Comment by fmatthies** [comment]
I uploaded a bug fix for `jsbd`; please pull the recent 2.3.0-SNAPSHOT branch and build your jsbd application again!

**Comment by egrygorova** [comment]
these are the results for 10-folds for fixed JSBD:

all : 12446
corr: 12421
fp :21
fn :4
R :0.9996780684104628
P :0.9983121684616622
F :0.9989946515462259
ACC : 0.9979913225132573
0: 0,999
1: 0,995
2: 0,997
3: 0,995
4: 0,997
5: 0,997
6: 0,999
7: 0,998
8: 1,000
9: 0,998
avg accuracy: 0,998
avg f-score: 0,999


Accuracy on cross validation: 0.9975798557915574

And for 2-folds:

all : 69589
corr: 69315
fp :184
fn :90
R :0.9987032634536417
P :0.997352479891797
F :0.9980274146172896
ACC : 0.9960625960999583
0: 0,997
1: 0,996
avg accuracy: 0,997
avg f-score: 0,998


Accuracy on cross validation: 0.9967611341988423

It's the same as before

**Comment by fmatthies** [comment]
> > all : 69589
> > corr: 69308
> > all : 12446
> > corr: 12427

> why do these differ? There should be an equal amount of sentences... How did you split?

Please look into it.

**Comment by egrygorova** [comment]
I think that the amount of sentences differs because it's the amount in each validation round.
If you have 10 rounds, there are less sentences in each round that in 2 rounds.

**Comment by fmatthies** [comment]
Are there now two new models for `biomed`?

**Comment by egrygorova** [comment]
yes they are under Jcore-projects in a pull request

**Comment by khituras** [comment]
I think, JTBD and JSBD models have also been retrained and are working, aren't they? Can this issue be closed?
